ALTER TABLE devices ALTER COLUMN last_connection TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE devices ALTER COLUMN linked_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE biometric_telemetry_samples ALTER COLUMN observed_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE baselines ALTER COLUMN calculated_at TYPE TIMESTAMP WITH TIME ZONE;
